import Editor,{DiffEditor,type OnMount}from"@monaco-editor/react";import{useEffect,useState}from"react";import{BRAND}from"../app/branding";import{useWorkspaceStore}from"../project/workspaceStore";import{workspaceApi}from"../project/workspaceApi";import{useUiStore}from"../ui/state/uiStore";import{useEditorStore}from"./editorStore";

type PromptMode="commands"|"files"|null;
let mountedEditor:Parameters<OnMount>[0]|null=null;
export function EditorSurface(){const workspace=useWorkspaceStore(s=>s.workspace);const choose=useWorkspaceStore(s=>s.choose);const toggleBottom=useUiStore(s=>s.toggleBottomPanel);const{tabs,activePath,diffPath,activate,change,save,saveAll,close,closeAll,viewDiff,open,checkExternal}=useEditorStore();const[closePath,setClosePath]=useState<string|null>(null);const[prompt,setPrompt]=useState<PromptMode>(null);const[query,setQuery]=useState("");const[results,setResults]=useState<string[]>([]);const[autosave,setAutosave]=useState(()=>localStorage.getItem("gravityforge.autosave")==="delay");const[restored,setRestored]=useState(false);const active=tabs.find(t=>t.path===activePath)??null;
 useEffect(()=>{const timer=window.setInterval(()=>void checkExternal(),2500);return()=>clearInterval(timer);},[checkExternal]);
 useEffect(()=>{if(workspace&&!restored){setRestored(true);try{const saved=JSON.parse(localStorage.getItem("gravityforge.editor")??"{}")as{paths?:string[];activePath?:string};void(async()=>{for(const path of saved.paths??[])await open(path);if(saved.activePath)activate(saved.activePath);})();}catch{/* Ignore invalid session data. */}}},[workspace,restored,open,activate]);
 useEffect(()=>{if(!autosave||!active?.dirty)return;const timer=window.setTimeout(()=>void save(active.path),1000);return()=>window.clearTimeout(timer);},[autosave,active?.content,active?.dirty,active?.path,save]);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(tabs.some(t=>t.dirty)){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[tabs]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey))return;if(event.key.toLowerCase()==="s"){event.preventDefault();void(event.shiftKey?saveAll():save());}else if(event.key.toLowerCase()==="w"){event.preventDefault();if(active&&!close(active.path))setClosePath(active.path);}else if(event.key.toLowerCase()==="p"){event.preventDefault();setPrompt(event.shiftKey?"commands":"files");setQuery("");}};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);},[active,close,save,saveAll]);
 useEffect(()=>{if(prompt==="files")void workspaceApi.search(query).then(setResults);else setResults([]);},[prompt,query]);
 const mount:OnMount=(editor,monaco)=>{mountedEditor=editor;editor.addAction({id:"gravityforge.format",label:"Format Document",keybindings:[monaco.KeyMod.Shift|monaco.KeyMod.Alt|monaco.KeyCode.KeyF],run:()=>editor.getAction("editor.action.formatDocument")?.run()});};
 const requestClose=(path:string)=>{if(!close(path))setClosePath(path);};const commands=[{name:"Open Project",run:()=>void choose()},{name:"Save",run:()=>void save()},{name:"Save All",run:()=>void saveAll()},{name:"Close File",run:()=>active&&requestClose(active.path)},{name:"Close All",run:()=>{if(!closeAll())setClosePath("*");}},{name:"Go to Line",run:()=>void mountedEditor?.getAction("editor.action.gotoLine")?.run()},{name:"Toggle Bottom Panel",run:toggleBottom},{name:"View Changes",run:()=>active&&viewDiff(active.path)}];
 return <section className="editor-surface"><div className="editor-tabs">{tabs.length?tabs.map(tab=><div className={`editor-tab ${tab.path===activePath?"active":""}`} key={tab.path} onClick={()=>activate(tab.path)}><span>{tab.filename}{tab.dirty?" ●":""}</span><button onClick={e=>{e.stopPropagation();requestClose(tab.path);}}>×</button></div>):<div className="editor-tab active">{workspace?"Project Map":"Welcome"}</div>}<div className="editor-actions"><select aria-label="Autosave" value={autosave?"delay":"off"} onChange={e=>{const enabled=e.target.value==="delay";setAutosave(enabled);localStorage.setItem("gravityforge.autosave",enabled?"delay":"off");}}><option value="off">Autosave: Off</option><option value="delay">Autosave: After Delay</option></select><button onClick={()=>void save()} disabled={!active?.dirty}>Save</button><button onClick={()=>void saveAll()} disabled={!tabs.some(t=>t.dirty)}>Save All</button>{active?<button onClick={()=>viewDiff(active.path)}>View Changes</button>:null}</div></div>
 {active?<><div className="breadcrumb">{active.path.split("/").join("  ›  ")}{active.large?"  ·  Large file (read-only)":""}{active.conflict?"  ·  External change conflict":""}</div><div className="monaco-host">{diffPath===active.path?<DiffEditor original={active.originalContent} modified={active.content} language={active.language} theme="vs-dark" options={{readOnly:true,renderSideBySide:true,minimap:{enabled:true}}}/>:<Editor path={`file:///${active.path}`} value={active.content} language={active.language} theme="vs-dark" onChange={value=>change(active.path,value??"")} onMount={mount} options={{readOnly:active.readOnly,minimap:{enabled:true},automaticLayout:true,wordWrap:"off",formatOnPaste:false}}/>}</div></>:workspace?<div className="project-map"><h1>{workspace.name}</h1><p>{workspace.root}</p><h3>Detected</h3><p>{workspace.projectInfo.detectedFrameworks.join(", ")||workspace.projectInfo.projectTypes.join(", ")||"No framework detected"}</p><h3>Available scripts</h3><pre>{Object.keys(workspace.projectInfo.package?.scripts??{}).join("\n")||"None"}</pre></div>:<div className="welcome-view"><div className="welcome-logo">{BRAND.shortName}</div><h1>{BRAND.name}</h1><p>{BRAND.tagline}</p><small>Open a local project to begin</small></div>}
 {prompt?<div className="palette-backdrop" onClick={()=>setPrompt(null)}><div className="palette" onClick={e=>e.stopPropagation()}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={prompt==="files"?"Quick Open…":"Command Palette…"}/><div>{prompt==="files"?results.map(path=><button key={path} onClick={()=>{void open(path);setPrompt(null);}}>{path}</button>):commands.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(c=><button key={c.name} onClick={()=>{c.run();setPrompt(null);}}>{c.name}</button>)}</div></div></div>:null}
 {closePath?<div className="palette-backdrop"><div className="unsaved-dialog"><h3>Unsaved changes</h3><p>Save changes before closing?</p><button onClick={()=>{const targets=closePath==="*"?tabs.filter(t=>t.dirty).map(t=>t.path):[closePath];void(async()=>{for(const path of targets)await save(path);if(closePath==="*")closeAll(true);else close(closePath,true);setClosePath(null);})();}}>Save</button><button onClick={()=>{if(closePath==="*")closeAll(true);else close(closePath,true);setClosePath(null);}}>Don&apos;t Save</button><button onClick={()=>setClosePath(null)}>Cancel</button></div></div>:null}</section>}
