import{create}from"zustand";import{workspaceApi}from"../project/workspaceApi";import{languageFor}from"./languages";
export interface EditorTab{path:string;filename:string;language:string;content:string;originalContent:string;dirty:boolean;readOnly:boolean;encoding:"UTF-8";lastModified:number;large:boolean;conflict:boolean}
interface State{tabs:EditorTab[];activePath:string|null;diffPath:string|null;error:string|null;open:(path:string)=>Promise<void>;activate:(path:string)=>void;change:(path:string,content:string)=>void;save:(path?:string)=>Promise<void>;saveAll:()=>Promise<void>;close:(path:string,force?:boolean)=>boolean;closeAll:(force?:boolean)=>boolean;viewDiff:(path:string|null)=>void;checkExternal:()=>Promise<void>}
const persist=(tabs:EditorTab[],activePath:string|null)=>localStorage.setItem("gravityforge.editor",JSON.stringify({paths:tabs.map(t=>t.path),activePath}));
export const useEditorStore=create<State>((set,get)=>({tabs:[],activePath:null,diffPath:null,error:null,
 open:async path=>{const existing=get().tabs.find(t=>t.path===path);if(existing){set({activePath:path});return;}const stat=await workspaceApi.stat(path);if(stat.size>20*1024*1024){set({error:"File exceeds the 20 MiB editor limit"});return;}const file=await workspaceApi.read(path);if(file.kind==="binary"){set({error:"Binary file"});return;}const tab:EditorTab={path,filename:path.split("/").pop()??path,language:languageFor(path),content:file.content,originalContent:file.content,dirty:false,readOnly:stat.readOnly||stat.size>5*1024*1024,encoding:"UTF-8",lastModified:stat.modifiedAt,large:stat.size>5*1024*1024,conflict:false};const tabs=[...get().tabs,tab];set({tabs,activePath:path,error:null});persist(tabs,path);},
 activate:path=>{set({activePath:path});persist(get().tabs,path);},change:(path,content)=>set(s=>({tabs:s.tabs.map(t=>t.path===path?{...t,content,dirty:content!==t.originalContent}:t)})),
 save:async path=>{const target=path??get().activePath;if(!target)return;const tab=get().tabs.find(t=>t.path===target);if(!tab||tab.readOnly)return;const stat=await workspaceApi.write(tab.path,tab.content);set(s=>({tabs:s.tabs.map(t=>t.path===target?{...t,originalContent:t.content,dirty:false,lastModified:stat.modifiedAt,conflict:false}:t),error:null}));},
 saveAll:async()=>{for(const tab of get().tabs.filter(t=>t.dirty&&!t.readOnly))await get().save(tab.path);},
 close:(path,force=false)=>{const tab=get().tabs.find(t=>t.path===path);if(tab?.dirty&&!force)return false;const tabs=get().tabs.filter(t=>t.path!==path);const activePath=get().activePath===path?(tabs.at(-1)?.path??null):get().activePath;set({tabs,activePath,diffPath:get().diffPath===path?null:get().diffPath});persist(tabs,activePath);return true;},
 closeAll:(force=false)=>{if(!force&&get().tabs.some(t=>t.dirty))return false;set({tabs:[],activePath:null,diffPath:null});persist([],null);return true;},viewDiff:diffPath=>set({diffPath}),
 checkExternal:async()=>{for(const tab of get().tabs){try{const stat=await workspaceApi.stat(tab.path);if(stat.modifiedAt!==tab.lastModified){if(tab.dirty)set(s=>({tabs:s.tabs.map(t=>t.path===tab.path?{...t,conflict:true}:t)}));else{const file=await workspaceApi.read(tab.path);if(file.kind==="text")set(s=>({tabs:s.tabs.map(t=>t.path===tab.path?{...t,content:file.content,originalContent:file.content,lastModified:stat.modifiedAt}:t)}));}}}catch{set({error:`File unavailable: ${tab.path}`});}}}
}));
